export type Verdict = "BACKED" | "MIXED" | "DEBUNKED";

export type Trend = {
  slug: string;
  name: string;
  /** The user's original raw search words, when this trend came from a real
   *  search (generated trends). Used for community/Reddit lookups so they
   *  match on everyday wording rather than a scientific display title.
   *  Undefined for curated trends, which fall back to `name`. */
  query?: string;
  category: string; // matches CATEGORIES slugs
  verdict: Verdict;
  oneLiner: string;
  communityVerdict: string;
  safetyNote: string;
  studies: number;
  confidence: "high" | "moderate" | "low";
  sentiment: number; // 0-100
  updated: string; // YYYY-MM-DD
  evidence: string[];
  quotes: { handle: string; text: string; url: string }[];
  related: string[]; // slugs
  /** Real per-article PubMed links, in the same order as `evidence` where
   *  available. Empty for curated trends (no article was ever fetched for
   *  them) — falls back to a plain name search in that case. */
  sourceUrls: string[];
};

export const CATEGORIES = [
  { slug: "skincare", label: "SKINCARE" },
  { slug: "haircare", label: "HAIRCARE" },
  { slug: "supplements", label: "SUPPLEMENTS" },
  { slug: "nutrition", label: "NUTRITION" },
  { slug: "sleep", label: "SLEEP" },
  { slug: "gut-health", label: "GUT HEALTH" },
  { slug: "fitness", label: "FITNESS" },
  { slug: "mental-wellness", label: "MENTAL WELLNESS" },
];

export const TRENDS: Trend[] = [
  {
    slug: "daily-spf",
    name: "Daily SPF 30+ Sunscreen",
    category: "skincare",
    verdict: "BACKED",
    oneLiner: "Daily broad-spectrum sunscreen meaningfully reduces photoaging and skin-cancer risk.",
    studies: 142,
    confidence: "high",
    sentiment: 89,
    updated: "2026-05-14",
    evidence: [
      "Multiple RCTs show daily SPF use reduces visible photoaging within 12 months.",
      "Long-term cohort studies link daily use to lower rates of squamous cell carcinoma.",
      "Broad-spectrum formulas outperform UVB-only on pigmentation outcomes.",
      "Reapplication every ~2 hours sun exposure is required to retain stated SPF.",
    ],
    quotes: [],
    communityVerdict: "Widely loved as a non-negotiable step — the main complaint is dated formulas leaving a white cast, which modern ones have mostly fixed.",
    safetyNote: "No notable risks for typical use — just watch for fragrance/chemical-filter sensitivity if you have reactive skin.",
    sourceUrls: [],
    related: ["retinol", "vitamin-c-serum", "niacinamide"],
  },
  {
    slug: "retinol",
    name: "Retinoids for Wrinkles",
    category: "skincare",
    verdict: "BACKED",
    oneLiner: "Topical retinoids reliably reduce fine lines and improve skin texture over months.",
    studies: 96,
    confidence: "high",
    sentiment: 84,
    updated: "2026-04-22",
    evidence: [
      "Tretinoin shows the strongest evidence for wrinkle reduction across decades of trials.",
      "OTC retinol takes 12+ weeks to show measurable change in most users.",
      "Pairing with SPF is required — retinoids increase photosensitivity.",
    ],
    quotes: [],
    communityVerdict: "Users consistently describe an initial adjustment period (dryness, mild peeling) followed by real, lasting payoff once skin adapts.",
    safetyNote: "Avoid during pregnancy or while trying to conceive; increases sun sensitivity, so daily SPF is essential alongside it.",
    sourceUrls: [],
    related: ["daily-spf", "vitamin-c-serum", "niacinamide"],
  },
  {
    slug: "vitamin-c-serum",
    name: "Vitamin C Serum",
    category: "skincare",
    verdict: "BACKED",
    oneLiner: "L-ascorbic acid at 10–20% brightens, supports collagen, and boosts SPF performance.",
    studies: 58,
    confidence: "moderate",
    sentiment: 78,
    updated: "2026-03-30",
    evidence: [
      "L-ascorbic acid 10–20% shows antioxidant and brightening effects in clinical trials.",
      "Formulation stability matters — opaque packaging and pH < 3.5 preserve potency.",
      "Pairs synergistically with sunscreen in photoprotection studies.",
    ],
    quotes: [],
    communityVerdict: "People like the brightening effect but frequently complain about serums oxidizing before they finish the bottle.",
    safetyNote: "Can cause mild irritation or tingling at higher concentrations, especially alongside other actives like retinol.",
    sourceUrls: [],
    related: ["daily-spf", "retinol", "niacinamide"],
  },
  {
    slug: "niacinamide",
    name: "Niacinamide for Redness",
    category: "skincare",
    verdict: "BACKED",
    oneLiner: "Topical niacinamide 4–5% reduces redness, sebum, and supports the skin barrier.",
    studies: 41,
    confidence: "moderate",
    sentiment: 81,
    updated: "2026-02-18",
    evidence: [
      "4–5% niacinamide reduces transepidermal water loss in barrier-compromised skin.",
      "Modest reduction in sebum production and pore appearance shown in trials.",
      "Plays well with almost everything — low irritation profile.",
    ],
    quotes: [],
    communityVerdict: "Consistently praised as gentle and easy to layer with other actives, with several users reporting it calmed redness within weeks.",
    safetyNote: "Very well tolerated; rare flushing has been reported at high doses, mostly with oral (not topical) niacinamide.",
    sourceUrls: [],
    related: ["daily-spf", "retinol", "vitamin-c-serum"],
  },
  {
    slug: "slugging",
    name: "Slugging",
    category: "skincare",
    verdict: "BACKED",
    oneLiner: "Sealing skin with petrolatum overnight reduces water loss for dry/compromised skin.",
    studies: 22,
    confidence: "moderate",
    sentiment: 74,
    updated: "2026-01-12",
    evidence: [
      "Petrolatum is the most effective occlusive in studies of TEWL reduction.",
      "Most useful in winter, post-procedure, or with eczema-prone skin.",
      "Not recommended for acne-prone skin without testing first.",
    ],
    quotes: [],
    communityVerdict: "A favorite for winter or post-retinoid nights, though people joke about the messy pillowcase tradeoff.",
    safetyNote: "Can trap oil and worsen breakouts on acne-prone skin — patch test before making it a nightly habit.",
    sourceUrls: [],
    related: ["retinol", "daily-spf", "snail-mucin"],
  },
  {
    slug: "snail-mucin",
    name: "Snail Mucin",
    category: "skincare",
    verdict: "BACKED",
    oneLiner: "Snail secretion filtrate shows real evidence for hydration and wound-repair markers.",
    studies: 19,
    confidence: "moderate",
    sentiment: 72,
    updated: "2025-12-08",
    evidence: [
      "Clinical studies show improvement in hydration and post-procedure recovery markers.",
      "Effects are real but modest vs. heavily marketed claims.",
      "Generally well tolerated; allergic reactions are rare but documented.",
    ],
    quotes: [],
    communityVerdict: "One of the rare K-beauty trends people say lived up to the hype for hydration, though anti-aging claims get pushback.",
    safetyNote: "Rare allergic reactions have been documented; discontinue if you notice redness or itching.",
    sourceUrls: [],
    related: ["niacinamide", "slugging", "hyaluronic-acid"],
  },
  {
    slug: "hyaluronic-acid",
    name: "Hyaluronic Acid",
    category: "skincare",
    verdict: "BACKED",
    oneLiner: "Topical HA hydrates the upper skin layers — apply to damp skin and seal.",
    studies: 64,
    confidence: "high",
    sentiment: 80,
    updated: "2026-04-02",
    evidence: [
      "Demonstrated humectant effect in stratum corneum hydration studies.",
      "Apply to damp skin and seal with moisturizer — dry-air application can backfire.",
      "Multiple molecular weights penetrate differently; impact on wrinkles is modest.",
    ],
    quotes: [],
    communityVerdict: "Generally well liked, but a recurring complaint is that applying it to dry (not damp) skin can backfire and pull moisture out.",
    safetyNote: "No significant risks for topical use; applying it in very dry air without sealing can occasionally worsen dryness.",
    sourceUrls: [],
    related: ["niacinamide", "snail-mucin", "daily-spf"],
  },
  {
    slug: "jade-roller",
    name: "Jade Roller",
    category: "skincare",
    verdict: "MIXED",
    oneLiner: "Brief de-puffing is real; structural skin benefits are not.",
    studies: 9,
    confidence: "low",
    sentiment: 52,
    updated: "2025-11-04",
    evidence: [
      "Cold massage temporarily reduces puffiness via vasoconstriction.",
      "No evidence for collagen stimulation or 'lymphatic drainage' claims.",
      "Cleanliness matters more than the stone — bacteria buildup is common.",
    ],
    quotes: [],
    communityVerdict: "Most describe it as a pleasant but purely cosmetic ritual — nice in the moment, with no lasting skin change.",
    safetyNote: "Low risk, but unclean stones can harbor bacteria — clean it regularly, especially if used on broken-out skin.",
    sourceUrls: [],
    related: ["gua-sha", "dry-brushing", "snail-mucin"],
  },
  {
    slug: "gua-sha",
    name: "Gua Sha",
    category: "skincare",
    verdict: "MIXED",
    oneLiner: "Temporary lift and de-puffing; lasting facial sculpting claims aren't supported.",
    studies: 11,
    confidence: "low",
    sentiment: 58,
    updated: "2025-10-21",
    evidence: [
      "Short-term de-puffing and improved circulation in small studies.",
      "No evidence for lasting jawline reshaping from facial gua sha.",
      "Technique matters — heavy pressure can bruise without benefit.",
    ],
    quotes: [],
    communityVerdict: "People enjoy the morning de-puffing ritual but are skeptical of any lasting facial-sculpting claims.",
    safetyNote: "Heavy pressure can bruise or irritate skin — use gentle strokes, especially on sensitive or thin skin.",
    sourceUrls: [],
    related: ["jade-roller", "dry-brushing", "snail-mucin"],
  },
  {
    slug: "activated-charcoal",
    name: "Activated Charcoal Masks",
    category: "skincare",
    verdict: "DEBUNKED",
    oneLiner: "Won't 'pull toxins.' Peel-off versions can damage your skin barrier.",
    studies: 14,
    confidence: "high",
    sentiment: 38,
    updated: "2026-01-30",
    evidence: [
      "No evidence charcoal masks remove toxins from skin or pores.",
      "Peel-off formulations can rip out vellus hair and damage stratum corneum.",
      "May reduce surface oil briefly but no lasting acne or pore benefit.",
    ],
    quotes: [],
    communityVerdict: "Frequent complaints about peel-off masks physically hurting to remove, with little payoff beyond a brief matte look.",
    safetyNote: "Peel-off formulas can damage the skin barrier and pull out fine hair — avoid on sensitive or broken skin.",
    sourceUrls: [],
    related: ["jade-roller", "dry-brushing", "gua-sha"],
  },
  {
    slug: "dry-brushing",
    name: "Dry Brushing",
    category: "skincare",
    verdict: "MIXED",
    oneLiner: "Mild exfoliation, real. Cellulite reduction and lymphatic detox claims, no.",
    studies: 7,
    confidence: "low",
    sentiment: 48,
    updated: "2025-09-10",
    evidence: [
      "Mechanical exfoliation can smooth skin temporarily.",
      "No reliable evidence for cellulite reduction or 'detox' effects.",
      "Aggressive use can damage skin barrier — light pressure only.",
    ],
    quotes: [],
    communityVerdict: "People enjoy the sensory ritual but are clear-eyed that it doesn't deliver on cellulite or detox claims.",
    safetyNote: "Aggressive brushing can cause micro-tears in the skin barrier — light pressure only, avoid broken or irritated skin.",
    sourceUrls: [],
    related: ["jade-roller", "gua-sha", "activated-charcoal"],
  },

  // HAIRCARE
  {
    slug: "rosemary-oil",
    name: "Rosemary Oil for Hair",
    category: "haircare",
    verdict: "MIXED",
    oneLiner: "One trial vs. minoxidil showed comparable results; broader evidence is thin.",
    studies: 12,
    confidence: "moderate",
    sentiment: 67,
    updated: "2026-02-04",
    evidence: [
      "A 2015 RCT showed comparable hair count to 2% minoxidil at 6 months.",
      "Replication is limited; mechanism is not fully understood.",
      "Generally safe; dilute in carrier oil to avoid scalp irritation.",
    ],
    quotes: [],
    communityVerdict: "Seen as a low-risk experiment worth trying, with scattered reports of success but wide acknowledgment that results vary person to person.",
    safetyNote: "Dilute in a carrier oil before scalp use — applying it undiluted can cause irritation or a burning sensation.",
    sourceUrls: [],
    related: ["biotin", "collagen-peptides", "slugging"],
  },
  {
    slug: "biotin",
    name: "Biotin for Hair",
    category: "haircare",
    verdict: "MIXED",
    oneLiner: "Only helps if you're actually deficient — most people aren't.",
    studies: 18,
    confidence: "moderate",
    sentiment: 49,
    updated: "2026-03-01",
    evidence: [
      "Effective only in documented biotin deficiency, which is uncommon.",
      "Can interfere with lab tests including thyroid and cardiac markers.",
      "No evidence supplementation grows hair in non-deficient adults.",
    ],
    quotes: [],
    communityVerdict: "Mixed reception — people without a documented deficiency mostly report no noticeable hair changes, and some flag it can skew bloodwork.",
    safetyNote: "Can interfere with common lab tests, including thyroid and cardiac markers — tell your doctor if you're taking it before bloodwork.",
    sourceUrls: [],
    related: ["rosemary-oil", "collagen-peptides", "ashwagandha"],
  },

  // SUPPLEMENTS
  {
    slug: "collagen-peptides",
    name: "Collagen Peptides",
    category: "supplements",
    verdict: "BACKED",
    oneLiner: "10–15g/day shows modest improvements in skin elasticity and joint comfort.",
    studies: 73,
    confidence: "moderate",
    sentiment: 76,
    updated: "2026-04-15",
    evidence: [
      "Meta-analyses show modest improvement in skin elasticity at 8–12 weeks.",
      "Some evidence for joint discomfort reduction in active populations.",
      "Type and dose matter — hydrolyzed peptides at 10–15g/day are most studied.",
    ],
    quotes: [],
    communityVerdict: "People report modest but real improvements, especially for joint comfort, while cautioning against expecting dramatic skin transformation.",
    safetyNote: "Generally well tolerated; check sourcing (bovine/marine) if you have relevant allergies or dietary restrictions.",
    sourceUrls: [],
    related: ["creatine", "ashwagandha", "magnesium-sleep"],
  },
  {
    slug: "ashwagandha",
    name: "Ashwagandha",
    category: "supplements",
    verdict: "BACKED",
    oneLiner: "Clinically reduces self-reported stress and cortisol at 300–600mg/day.",
    studies: 47,
    confidence: "moderate",
    sentiment: 79,
    updated: "2026-03-19",
    evidence: [
      "RCTs show reductions in perceived stress and serum cortisol over 8 weeks.",
      "Effects on sleep quality and anxiety are consistent across studies.",
      "Avoid with thyroid medication and during pregnancy.",
    ],
    quotes: [],
    communityVerdict: "Strong anecdotal support for stress and sleep, with several users describing a noticeable shift within the first month.",
    safetyNote: "Avoid during pregnancy and if you have a thyroid condition or take thyroid medication — it can affect thyroid hormone levels.",
    sourceUrls: [],
    related: ["magnesium-sleep", "melatonin", "creatine"],
  },
  {
    slug: "creatine",
    name: "Creatine Monohydrate",
    category: "supplements",
    verdict: "BACKED",
    oneLiner: "The most-studied performance supplement. 3–5g/day, period.",
    studies: 218,
    confidence: "high",
    sentiment: 88,
    updated: "2026-05-02",
    evidence: [
      "Largest evidence base of any sports supplement; strength and lean mass gains.",
      "Emerging evidence for cognitive benefits under sleep deprivation.",
      "Loading phase is optional — 3–5g daily reaches saturation in ~4 weeks.",
    ],
    quotes: [],
    communityVerdict: "Near-universal endorsement as the one supplement worth taking — consistently described as cheap, safe, and effective.",
    safetyNote: "Very well studied and safe for healthy adults; stay well hydrated, and check with a doctor first if you have kidney disease.",
    sourceUrls: [],
    related: ["ashwagandha", "collagen-peptides", "magnesium-sleep"],
  },
  {
    slug: "melatonin",
    name: "Melatonin",
    category: "sleep",
    verdict: "BACKED",
    oneLiner: "Effective for jet lag and shift work at 0.3–0.5mg. Most OTC doses are way too high.",
    studies: 132,
    confidence: "high",
    sentiment: 71,
    updated: "2026-04-08",
    evidence: [
      "Strongest evidence for circadian shifts: jet lag, delayed sleep phase, shift work.",
      "Low doses (0.3–0.5mg) outperform 5–10mg doses in most trials.",
      "US OTC dosing is typically 10–20× the effective dose.",
    ],
    quotes: [],
    communityVerdict: "Generally positive, with experienced users specifically pushing back on high OTC doses in favor of smaller, better-timed amounts.",
    safetyNote: "Can cause grogginess if the dose is too high; avoid combining with alcohol or other sedatives.",
    sourceUrls: [],
    related: ["magnesium-sleep", "ashwagandha"],
  },
  {
    slug: "magnesium-sleep",
    name: "Magnesium for Sleep",
    category: "sleep",
    verdict: "BACKED",
    oneLiner: "Glycinate form, 200–400mg, modest but real sleep-quality improvements.",
    studies: 38,
    confidence: "moderate",
    sentiment: 75,
    updated: "2026-03-25",
    evidence: [
      "Magnesium glycinate shows modest improvements in sleep onset and quality.",
      "Most useful in adults with low dietary intake or elevated stress.",
      "Oxide form is poorly absorbed — use glycinate or threonate.",
    ],
    quotes: [],
    communityVerdict: "Well liked for sleep quality, with several users specifically calling out the glycinate form as key to feeling a difference.",
    safetyNote: "High doses can cause digestive upset (loose stools); those with kidney issues should check with a doctor first.",
    sourceUrls: [],
    related: ["melatonin", "ashwagandha"],
  },

  // NUTRITION
  {
    slug: "celery-juice",
    name: "Celery Juice Detox",
    category: "nutrition",
    verdict: "DEBUNKED",
    oneLiner: "No 'detox' mechanism exists. You bought expensive celery water.",
    studies: 4,
    confidence: "high",
    sentiment: 22,
    updated: "2026-02-12",
    evidence: [
      "No clinical evidence supports any 'detox' claim for celery juice.",
      "Healthy livers and kidneys already detoxify — no juice required.",
      "Some benefit comes from added hydration and produce intake generally.",
    ],
    quotes: [],
    communityVerdict: "Broad skepticism — most people see it as an overhyped ritual rather than anything with real detox benefits.",
    safetyNote: "High in oxalates — worth discussing with a doctor if you have a history of kidney stones.",
    sourceUrls: [],
    related: ["activated-charcoal", "turmeric"],
  },
  {
    slug: "turmeric",
    name: "Turmeric for Inflammation",
    category: "nutrition",
    verdict: "BACKED",
    oneLiner: "Curcumin with piperine shows real anti-inflammatory effects in joint and metabolic studies.",
    studies: 89,
    confidence: "moderate",
    sentiment: 73,
    updated: "2026-04-19",
    evidence: [
      "Curcumin shows measurable reduction in CRP and joint pain across meta-analyses.",
      "Bioavailability is poor without piperine or lipid carriers.",
      "Effects are modest — not a substitute for NSAIDs in acute inflammation.",
    ],
    quotes: [],
    communityVerdict: "Positive but conditional — people who see results emphasize that absorption-boosting formulation makes the difference.",
    safetyNote: "Can interact with blood thinners and may upset the stomach at high doses — check with a doctor if you're on medication.",
    sourceUrls: [],
    related: ["ashwagandha", "collagen-peptides"],
  },
  {
    slug: "intermittent-fasting",
    name: "Intermittent Fasting",
    category: "nutrition",
    verdict: "MIXED",
    oneLiner: "Works mainly through calorie reduction — no magic metabolic effect.",
    studies: 64,
    confidence: "moderate",
    sentiment: 60,
    updated: "2026-03-08",
    evidence: [
      "Most weight-loss benefit is from reduced caloric intake, not timing per se.",
      "Some metabolic markers improve, but matched-calorie comparisons show small effects.",
      "May worsen disordered eating patterns — not for everyone.",
    ],
    quotes: [],
    communityVerdict: "Reception is practical rather than enthusiastic — people frame it as a scheduling tool that works if it fits your lifestyle, not a metabolic hack.",
    safetyNote: "Not recommended for anyone with a history of disordered eating; those on diabetes medication should consult a doctor first.",
    sourceUrls: [],
    related: ["creatine", "ashwagandha"],
  },
  {
    slug: "oil-pulling",
    name: "Oil Pulling",
    category: "gut-health",
    verdict: "DEBUNKED",
    oneLiner: "Doesn't whiten teeth or 'detox.' Brush, floss, repeat.",
    studies: 16,
    confidence: "high",
    sentiment: 29,
    updated: "2026-01-22",
    evidence: [
      "No reliable evidence for whitening or systemic detox claims.",
      "May slightly reduce plaque vs. nothing, but inferior to brushing and flossing.",
      "Linked to occasional lipoid pneumonia from accidental aspiration.",
    ],
    quotes: [],
    communityVerdict: "Mostly dismissed as an unnecessary extra step — people default back to recommending standard brushing and flossing.",
    safetyNote: "Rare but documented risk of lipoid pneumonia if the oil is accidentally inhaled/aspirated — don't substitute it for brushing.",
    sourceUrls: [],
    related: ["celery-juice", "activated-charcoal"],
  },
];

export function trendBySlug(slug: string): Trend | undefined {
  return TRENDS.find((t) => t.slug === slug);
}

export function trendsByCategory(slug: string): Trend[] {
  return TRENDS.filter((t) => t.category === slug);
}

export function categoryBySlug(slug: string) {
  return CATEGORIES.find((c) => c.slug === slug);
}
