/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrendSlugRouteImport } from './routes/trend.$slug'
import { Route as SearchQueryRouteImport } from './routes/search.$query'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendSlugRoute = TrendSlugRouteImport.update({
  id: '/trend/$slug',
  path: '/trend/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchQueryRoute = SearchQueryRouteImport.update({
  id: '/search/$query',
  path: '/search/$query',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/category/$slug': typeof CategorySlugRoute
  '/search/$query': typeof SearchQueryRoute
  '/trend/$slug': typeof TrendSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/category/$slug': typeof CategorySlugRoute
  '/search/$query': typeof SearchQueryRoute
  '/trend/$slug': typeof TrendSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/category/$slug': typeof CategorySlugRoute
  '/search/$query': typeof SearchQueryRoute
  '/trend/$slug': typeof TrendSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/category/$slug'
    | '/search/$query'
    | '/trend/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/category/$slug' | '/search/$query' | '/trend/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/category/$slug'
    | '/search/$query'
    | '/trend/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CategorySlugRoute: typeof CategorySlugRoute
  SearchQueryRoute: typeof SearchQueryRoute
  TrendSlugRoute: typeof TrendSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend/$slug': {
      id: '/trend/$slug'
      path: '/trend/$slug'
      fullPath: '/trend/$slug'
      preLoaderRoute: typeof TrendSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/$query': {
      id: '/search/$query'
      path: '/search/$query'
      fullPath: '/search/$query'
      preLoaderRoute: typeof SearchQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CategorySlugRoute: CategorySlugRoute,
  SearchQueryRoute: SearchQueryRoute,
  TrendSlugRoute: TrendSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
